import Link from 'next/link';

const confidences = [['Low', '10%', '±1'], ['Medium', '40%', '±2'], ['High', '70%', '±3'], ['All-In', '100%', '±5']];

export default function RulesPage() {
  return <main id="main-content" tabIndex={-1} className="page-shell"><article className="mx-auto max-w-4xl">
    <p className="eyebrow">Read. Decide. Reveal.</p><h1 className="mt-2 text-4xl font-black">How to play</h1>
    <p className="mt-3 max-w-2xl text-lg text-son-textSecondary">Study disguised market history, make your call, and beat the reveal. Every bankroll is fictional.</p>
    <div className="mt-8 grid gap-5 md:grid-cols-2">
      <section className="panel p-6"><h2 className="text-xl font-bold">Classic calls</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-relaxed text-son-textSecondary"><li>Read the clues and pre-decision chart.</li><li>Optionally name the hidden company.</li><li>Choose Long, Short, or Pass.</li><li>Choose confidence, lock in, and reveal.</li></ol></section>
      <section className="panel p-6"><h2 className="text-xl font-bold">Confidence</h2><div className="mt-4 grid grid-cols-2 gap-2">{confidences.map(([name, pct, signal]) => <div className="rounded-xl bg-son-surface p-3" key={name}><p className="font-bold">{name} · {pct}</p><p className="text-xs text-son-textMuted">Signal: {signal}</p></div>)}</div><p className="mt-3 text-xs text-son-textMuted">A wrong All-In call loses the entire stake and ends the run.</p></section>
      <section className="panel p-6"><h2 className="text-xl font-bold">Scoring</h2><p className="mt-3 text-sm leading-relaxed text-son-textSecondary">Bankroll is the primary score. Signal Score rewards accurate, confident calls. A correct company call adds 2 Signal; a wrong guess subtracts 1. Pass leaves bankroll unchanged, subtracts 0.25 Signal, and preserves—but does not grow—your streak.</p></section>
      <section className="panel p-6"><h2 className="text-xl font-bold">Classic & Daily</h2><ul className="mt-3 space-y-3 text-sm leading-relaxed text-son-textSecondary"><li><strong className="text-son-text">Classic:</strong> Easy is 10 rounds/$12,500, Medium is 15/$10,000, and Hard is 20/$7,500. Guests may play.</li><li><strong className="text-son-text">Daily:</strong> the same 10 mixed-difficulty rounds for everyone. Sign-in is required; replay freely and your best completed attempt for the UTC date ranks.</li></ul></section>
      <section className="panel p-6"><p className="eyebrow">No calls or confidence</p><h2 className="mt-2 text-xl font-bold">Portfolio Draft</h2><p className="mt-3 text-sm leading-relaxed text-son-textSecondary">Six hidden Medium companies share one compatible historical window. Choose exactly three; a fictional $10,000 splits equally. The reveal shows all six returns, your final value, the optimal three, and your gap. There is no Signal Score or MVP leaderboard. Guests may play; signed-in results save.</p><Link href="/play/draft" className="button-secondary mt-5 w-full">Play Portfolio Draft</Link></section>
      <section className="panel p-6"><p className="eyebrow">Two signed-in players</p><h2 className="mt-2 text-xl font-bold">Friend Battle</h2><p className="mt-3 text-sm leading-relaxed text-son-textSecondary">One immutable invite gives both players the same ordered Classic-style rounds. Both ready before each round; optional timers are off, 30, 60, or 120 seconds. Missing the deadline becomes Pass. Bankroll wins, Signal Score breaks ties, and unfinished battles expire after 24 hours with no winner.</p><p className="mt-3 text-xs leading-relaxed text-son-textMuted">Current-round choices stay private until both calls settle. Bankruptcy ends the battle immediately; simultaneous bankruptcy uses the same tiebreak.</p><Link href="/play/battle" className="button-secondary mt-5 w-full">Open Friend Battles</Link></section>
    </div>
  </article></main>;
}
